// ============================================================
 //  ViewTube – Mock Data
//  All videos, channels, and comments used across the app
// ============================================================

const COLORS = ['#d32f2f','#1565c0','#2e7d32','#6a1b9a','#e65100','#00695c','#ad1457','#0277bd'];
const ICONS  = ['🎵','🎮','💻','🔬','📰','⚽','🍳','✈️','🎬','📚','🌿','🏋️'];

const videos = [
  {
    id: 'v1',
    title: "Building a Full-Stack App with React & Node.js in 2024",
    channel: "CodeWithMe",
    channelId: "cwm",
    avatar: "C",
    color: "#1565c0",
    views: "1.2M views",
    date: "3 days ago",
    duration: "42:18",
    category: "coding",
    likes: 48200,
    subs: "620K",
    description: "In this comprehensive tutorial, we build a complete full-stack application from scratch using React on the frontend and Node.js/Express on the backend. We cover authentication, database integration with PostgreSQL, and deployment to AWS.\n\nTimestamps:\n0:00 – Introduction\n5:30 – Project setup\n12:00 – Backend API\n25:00 – Frontend React\n38:00 – Deployment\n\nCode on GitHub: github.com/codewithme",
    icon: "💻",
    thumbnail: window.THUMBNAILS.coding[Math.floor(Math.random() * window.THUMBNAILS.coding.length)],
    videoUrl: "/stream/v1_720p.mp4",
    comments: [
      { author: "DevJane", text: "This is exactly what I needed! The deployment section saved me hours.", likes: 234, time: "2 days ago" },
      { author: "TechMike", text: "Great tutorial! One question – can we use MongoDB instead of PostgreSQL?", likes: 87, time: "1 day ago" },
      { author: "CodeLearner99", text: "Best React tutorial of 2024, no doubt.", likes: 156, time: "12 hours ago" },
    ]
  },
  {
    id: 'v2',
    title: "10 JavaScript Tricks You Didn't Know Existed",
    channel: "TechWorld",
    channelId: "tw",
    avatar: "T",
    color: "#d32f2f",
    views: "4.7M views",
    date: "1 week ago",
    duration: "15:44",
    category: "coding",
    likes: 182000,
    subs: "2.1M",
    description: "Discover 10 powerful JavaScript tricks that will level up your code. From optional chaining to nullish coalescing and beyond!\n\nFollow us on Twitter: @TechWorld",
    icon: "💻",
    thumbnail: "https://i.ytimg.com/vi/eIrMbAcyC2g/mqdefault.jpg",
    videoUrl: "/stream/v2_720p.mp4",
    comments: [
      { author: "JSNinja", text: "The optional chaining one blew my mind 🤯", likes: 512, time: "5 days ago" },
      { author: "WebDev42", text: "Number 7 is something I use every day now, thanks!", likes: 204, time: "3 days ago" },
    ]
  },
  {
    id: 'v3',
    title: "Lo-fi Hip Hop Radio – Beats to Study/Relax 🎵",
    channel: "ChillVibes",
    channelId: "cv",
    avatar: "V",
    color: "#6a1b9a",
    views: "12M views",
    date: "2 months ago",
    duration: null,
    isLive: true,
    category: "music",
    likes: 520000,
    subs: "4.8M",
    description: "24/7 Lo-fi hip hop radio – the best beats to study, relax, and focus. Turn it up and get in the zone!",
    icon: "🎵",
    thumbnail: "https://i.ytimg.com/vi/jfKfPfyJRdk/mqdefault.jpg",
    videoUrl: "/stream/v3_720p.mp4",
    comments: [
      { author: "StudyQueen", text: "Listening to this while writing my thesis 💪", likes: 1200, time: "just now" },
      { author: "NightOwl88", text: "Couldn't sleep, this always helps. Thank you!", likes: 876, time: "1 hour ago" },
    ]
  },
  {
    id: 'v4',
    title: "The Most Beautiful Places on Earth 4K",
    channel: "NatureHub",
    channelId: "nh",
    avatar: "N",
    color: "#2e7d32",
    views: "8.9M views",
    date: "5 months ago",
    duration: "28:02",
    category: "travel",
    likes: 340000,
    subs: "3.2M",
    description: "Journey through the most breathtaking landscapes on our planet – from the Himalayas to the Amazon rainforest. Filmed in stunning 4K resolution.",
    icon: "🌿",
    thumbnail: "https://i.ytimg.com/vi/VB1s_uMWXno/mqdefault.jpg",
    videoUrl: "/stream/v4_720p.mp4",
    comments: [
      { author: "WanderlustSam", text: "This makes me want to quit my job and travel the world 😭", likes: 2100, time: "4 months ago" },
    ]
  },
  {
    id: 'v5',
    title: "Dark Souls III – Every Boss Ranked Worst to Best",
    channel: "GamingLore",
    channelId: "gl",
    avatar: "G",
    color: "#e65100",
    views: "2.1M views",
    date: "2 weeks ago",
    duration: "54:33",
    category: "gaming",
    likes: 89000,
    subs: "980K",
    description: "We rank every single boss in Dark Souls III from worst to best, considering design, difficulty, lore, and fun factor. Do you agree with our list?",
    icon: "🎮",
    thumbnail: "https://i.ytimg.com/vi/UBj24cc9NwE/mqdefault.jpg",
    videoUrl: "/stream/v5_720p.mp4",
    comments: [
      { author: "SoulsVet", text: "Nameless King at #1? A man of culture I see.", likes: 4500, time: "10 days ago" },
      { author: "CasualGamer", text: "I don't care what anyone says, Yhorm was fun!", likes: 312, time: "1 week ago" },
    ]
  },
  {
    id: 'v6',
    title: "How Black Holes Actually Work – A Deep Dive",
    channel: "CosmosExplained",
    channelId: "ce",
    avatar: "E",
    color: "#00695c",
    views: "6.3M views",
    date: "1 month ago",
    duration: "22:11",
    category: "science",
    likes: 275000,
    subs: "5.6M",
    description: "Black holes are one of the most fascinating objects in the universe. In this video, we break down exactly how they form, what happens at the event horizon, and what Stephen Hawking discovered about them.",
    icon: "🔬",
    thumbnail: "https://i.ytimg.com/vi/zKy91o-1D4U/mqdefault.jpg",
    videoUrl: "/stream/v6_720p.mp4",
    comments: [
      { author: "AstroEnthusiast", text: "The Hawking radiation explanation was so clear. Amazing!", likes: 1800, time: "3 weeks ago" },
    ]
  },
  {
    id: 'v7',
    title: "Gordon Ramsay's Perfect Scrambled Eggs – Technique Breakdown",
    channel: "CookingPro",
    channelId: "cp",
    avatar: "K",
    color: "#ad1457",
    views: "19M views",
    date: "2 years ago",
    duration: "8:47",
    category: "cooking",
    likes: 890000,
    subs: "7.2M",
    description: "We break down Gordon Ramsay's legendary scrambled egg technique step by step. The secret? Low heat, constant movement, and knowing when to stop.",
    icon: "🍳",
    thumbnail: "https://i.ytimg.com/vi/8uY5pCNujt8/mqdefault.jpg",
    videoUrl: "/stream/v7_720p.mp4",
    comments: [
      { author: "HomeChef", text: "Made these this morning. Life. Changed. Forever.", likes: 6700, time: "1 year ago" },
      { author: "EggLover42", text: "Still coming back to watch this every Sunday morning 😄", likes: 3200, time: "6 months ago" },
    ]
  },
  {
    id: 'v8',
    title: "Champions League 2024 – Top 10 Goals of the Season",
    channel: "FootballHighlights",
    channelId: "fh",
    avatar: "F",
    color: "#0277bd",
    views: "7.5M views",
    date: "3 weeks ago",
    duration: "11:22",
    category: "sports",
    likes: 310000,
    subs: "4.1M",
    description: "The top 10 most spectacular goals from the 2024 Champions League season. From long-range screamers to stunning solo efforts – this is pure football magic.",
    icon: "⚽",
    thumbnail: "https://i.ytimg.com/vi/dQw4w9WgXcQ/mqdefault.jpg",
    videoUrl: "/stream/v8_720p.mp4",
    comments: [
      { author: "FootballFan99", text: "Goal number 3 had me out of my seat! What a strike!", likes: 8900, time: "2 weeks ago" },
    ]
  },
  {
    id: 'v9',
    title: "Python in 2024 – Is It Still Worth Learning?",
    channel: "TechWorld",
    channelId: "tw",
    avatar: "T",
    color: "#d32f2f",
    views: "890K views",
    date: "4 days ago",
    duration: "18:05",
    category: "coding",
    likes: 34000,
    subs: "2.1M",
    description: "Python has been the #1 language for years – but in 2024, is it still the best choice for beginners and professionals? We break down the pros, cons, and alternatives.",
    icon: "💻",
    thumbnail: "https://i.ytimg.com/vi/_uQrJ0TkZlc/mqdefault.jpg",
    videoUrl: "/stream/v9_720p.mp4",
    comments: [
      { author: "PythonDev", text: "Python is here to stay. AI/ML alone guarantees it.", likes: 2100, time: "3 days ago" },
    ]
  },
  {
    id: 'v10',
    title: "Tokyo Travel Guide 2024 – The ULTIMATE 7-Day Itinerary",
    channel: "NatureHub",
    channelId: "nh",
    avatar: "N",
    color: "#2e7d32",
    views: "3.4M views",
    date: "3 months ago",
    duration: "35:50",
    category: "travel",
    likes: 156000,
    subs: "3.2M",
    description: "Your complete guide to Tokyo in 2024! We cover the best neighborhoods, must-eat foods, hidden gems, and how to navigate the city like a local. Perfect for first-time visitors.",
    icon: "✈️",
    thumbnail: "https://i.ytimg.com/vi/1Nrg1MH4L_g/mqdefault.jpg",
    videoUrl: "/stream/v10_720p.mp4",
    comments: [
      { author: "TokyoLover", text: "This guide is spot on! Used it for my trip last month.", likes: 3400, time: "2 months ago" },
    ]
  },
  {
    id: 'v11',
    title: "Elden Ring – Complete Lore Explained (All DLC)",
    channel: "GamingLore",
    channelId: "gl",
    avatar: "G",
    color: "#e65100",
    views: "5.1M views",
    date: "1 month ago",
    duration: "1:45:22",
    category: "gaming",
    likes: 234000,
    subs: "980K",
    description: "We dive deep into the lore of Elden Ring, including all the Shadow of the Erdtree DLC content. From the Greater Will to the Crucible – everything is connected.",
    icon: "🎮",
    thumbnail: "https://i.ytimg.com/vi/GiM5fjuI0LA/mqdefault.jpg",
videoUrl: "/stream/v1_720p.mp4",
    comments: [
      { author: "LoreMaster", text: "This is the definitive Elden Ring lore video. Bookmarked!", likes: 5600, time: "3 weeks ago" },
    ]
  },
  {
    id: 'v12',
    title: "Breaking News: Major Climate Agreement Reached",
    channel: "GlobalNews",
    channelId: "gn",
    avatar: "N",
    color: "#d32f2f",
    views: "420K views",
    date: "1 day ago",
    duration: "12:30",
    category: "news",
    likes: 8900,
    subs: "1.8M",
    description: "World leaders have reached a landmark climate agreement at the UN summit. We break down what this means for the planet and what happens next.",
    icon: "📰",
    thumbnail: "https://i.ytimg.com/vi/abc123/mqdefault.jpg",
videoUrl: "/stream/v2_720p.mp4",
    comments: [
      { author: "ClimateActivist", text: "Finally some good news! Let's hope they follow through.", likes: 1200, time: "18 hours ago" },
    ]
  },
  {
    id: 'v13',
    title: "Mastering CSS Grid in 20 Minutes",
    channel: "CodeWithMe",
    channelId: "cwm",
    avatar: "C",
    color: "#1565c0",
    views: "650K views",
    date: "1 week ago",
    duration: "20:00",
    category: "coding",
    likes: 28000,
    subs: "620K",
    description: "CSS Grid is the most powerful layout system in CSS. In this video, we cover everything you need to know to start using it in your projects.",
    icon: "💻",
    thumbnail: "https://i.ytimg.com/vi/X33V9Nl_7GQ/mqdefault.jpg",
    videoUrl: "/stream/v13_720p.mp4",
    comments: [
      { author: "CSSWizard", text: "Grid changed my life. This tutorial is perfect for beginners.", likes: 890, time: "5 days ago" },
    ]
  },
  {
    id: 'v14',
    title: "The Universe's Most Extreme Stars Explained",
    channel: "CosmosExplained",
    channelId: "ce",
    avatar: "E",
    color: "#00695c",
    views: "2.8M views",
    date: "2 months ago",
    duration: "25:40",
    category: "science",
    likes: 112000,
    subs: "5.6M",
    description: "We explore the most extreme stars in the universe – neutron stars, pulsars, magnetars, and more. These objects defy our understanding of physics.",
    icon: "🔬",
    thumbnail: "https://i.ytimg.com/vi/5E2YIfWVk4E/mqdefault.jpg",
    videoUrl: "/stream/v14_720p.mp4",
    comments: [
      { author: "SpaceFan", text: "Magnetars are terrifying. Great explanation!", likes: 2100, time: "1 month ago" },
    ]
  },
  {
    id: 'v15',
    title: "Street Food Tour – Bangkok's Best Hidden Gems",
    channel: "NatureHub",
    channelId: "nh",
    avatar: "N",
    color: "#2e7d32",
    views: "1.9M views",
    date: "4 months ago",
    duration: "30:20",
    category: "travel",
    likes: 78000,
    subs: "3.2M",
    description: "We hunt down the most authentic street food in Bangkok. From pad thai to mango sticky rice – these are the spots the locals love.",
    icon: "✈️",
    thumbnail: "https://i.ytimg.com/vi/4h8p6qM2iY0/mqdefault.jpg",
    videoUrl: "/stream/v15_720p.mp4",
    comments: [
      { author: "FoodieTraveler", text: "That pad thai place looks amazing! Adding to my list.", likes: 1500, time: "3 months ago" },
    ]
  },
  {
    id: 'v16',
    title: "React 18 New Features You Need to Know",
    channel: "CodeWithMe",
    channelId: "cwm",
    avatar: "C",
    color: "#1565c0",
    views: "950K views",
    date: "2 weeks ago",
    duration: "23:40",
    category: "coding",
    likes: 41000,
    subs: "620K",
    description: "Complete guide to React 18's concurrent features, automatic batching, and the new Suspense improvements.",
    icon: "💻",
    thumbnail: "https://i.ytimg.com/vi/wD4eKoaMnUc/mqdefault.jpg",
    videoUrl: "/stream/v16_720p.mp4",
    comments: [
      { author: "ReactDev", text: "Finally a clear explanation of concurrent features!", likes: 890, time: "1 week ago" },
    ]
  },
  {
    id: 'v17',
    title: "Cyberpunk 2077 – Ultimate Graphics Settings Guide",
    channel: "GamingLore",
    channelId: "gl",
    avatar: "G",
    color: "#6a1b9a",
    views: "3.2M views",
    date: "1 week ago",
    duration: "35:50",
    category: "gaming",
    likes: 145000,
    subs: "1.8M",
    description: "Maximize your graphics settings while maintaining smooth 60+ FPS gameplay in Cyberpunk 2077.",
    icon: "🎮",
    thumbnail: "https://i.ytimg.com/vi/TqL4-M3Djm8/mqdefault.jpg",
videoUrl: "/stream/v7_720p.mp4",
    comments: [
      { author: "CyberpunkFan", text: "Finally got 60 FPS with these settings! Thanks!", likes: 2300, time: "5 days ago" },
    ]
  },
  {
    id: 'v18',
    title: "Jazz Piano Covers – Relaxing Evening Music",
    channel: "ChillVibes",
    channelId: "cv",
    avatar: "C",
    color: "#e65100",
    views: "8.5M views",
    date: "2 months ago",
    duration: "∞",
    category: "music",
    likes: 380000,
    subs: "4.1M",
    description: "Smooth jazz piano covers of popular songs for your evening relaxation.",
    icon: "🎵",
    thumbnail: "https://i.ytimg.com/vi/7muskQ6nDUY/mqdefault.jpg",
    videoUrl: "/stream/v18_720p.mp4",
    comments: [
      { author: "JazzLover", text: "Perfect background music for studying!", likes: 4200, time: "1 month ago" },
    ]
  },
  {
    id: 'v19',
    title: "Northern Lights in Iceland – Aurora Photography",
    channel: "NatureHub",
    channelId: "nh",
    avatar: "N",
    color: "#2e7d32",
    views: "4.2M views",
    date: "3 months ago",
    duration: "31:30",
    category: "travel",
    likes: 168000,
    subs: "3.2M",
    description: "Capturing the magic of the northern lights in Iceland with professional photography techniques.",
    icon: "✈️",
    thumbnail: "https://i.ytimg.com/vi/2ZKPmydS6c8/mqdefault.jpg",
    videoUrl: "/stream/v19_720p.mp4",
    comments: [
      { author: "AuroraHunter", text: "Incredible shots! Planning my trip now.", likes: 1800, time: "2 months ago" },
    ]
  },
  {
    id: 'v20',
    title: "Machine Learning for Beginners – Neural Networks",
    channel: "TechWorld",
    channelId: "tw",
    avatar: "T",
    color: "#d32f2f",
    views: "1.8M views",
    date: "1 week ago",
    duration: "44:40",
    category: "coding",
    likes: 72000,
    subs: "2.1M",
    description: "Understanding the fundamentals of neural networks and how they power modern AI.",
    icon: "💻",
    thumbnail: "https://i.ytimg.com/vi/aircAruvnKk/mqdefault.jpg",
    videoUrl: "/stream/v20_720p.mp4",
    comments: [
      { author: "AILearner", text: "Finally understand neural networks! Great explanation.", likes: 1200, time: "4 days ago" },
    ]
  },
  {
    id: 'v21',
    title: "The Science of Cooking – Molecular Gastronomy",
    channel: "CookingPro",
    channelId: "cp",
    avatar: "C",
    color: "#ad1457",
    views: "5.6M views",
    date: "4 months ago",
    duration: "32:30",
    category: "cooking",
    likes: 245000,
    subs: "2.8M",
    description: "How science transforms cooking into art through molecular gastronomy techniques.",
    icon: "🍳",
    thumbnail: "https://i.ytimg.com/vi/R5KGYXLv6F8/mqdefault.jpg",
videoUrl: "/stream/v1_720p.mp4",
    comments: [
      { author: "ScienceChef", text: "Molecular gastronomy is fascinating! More please.", likes: 3100, time: "3 months ago" },
    ]
  },
  {
    id: 'v22',
    title: "Premier League 2024 – Best Goals Compilation",
    channel: "FootballHighlights",
    channelId: "fh",
    avatar: "F",
    color: "#0277bd",
    views: "9.2M views",
    date: "3 days ago",
    duration: "14:50",
    category: "sports",
    likes: 420000,
    subs: "5.2M",
    description: "The most incredible goals from the 2023-24 Premier League season.",
    icon: "⚽",
    thumbnail: "https://i.ytimg.com/vi/5s9-vEjSvs8/mqdefault.jpg",
videoUrl: "/stream/v2_720p.mp4",
    comments: [
      { author: "FootballFan", text: "That Salah goal was insane! 🔥", likes: 5800, time: "1 day ago" },
    ]
  },
  {
    id: 'v23',
    title: "SpaceX Starship – Mars Mission Update",
    channel: "CosmosExplained",
    channelId: "ce",
    avatar: "C",
    color: "#00695c",
    views: "7.8M views",
    date: "5 days ago",
    duration: "28:00",
    category: "science",
    likes: 345000,
    subs: "4.5M",
    description: "Latest developments in SpaceX's Starship and humanity's journey to Mars.",
    icon: "🔬",
    thumbnail: "https://i.ytimg.com/vi/3px_5z_1Jd4/mqdefault.jpg",
videoUrl: "/stream/v3_720p.mp4",
    comments: [
      { author: "SpaceEnthusiast", text: "Can't wait for Mars missions! 🚀", likes: 4200, time: "3 days ago" },
    ]
  },
  {
    id: 'v24',
    title: "TypeScript Advanced Patterns and Tips",
    channel: "CodeWithMe",
    channelId: "cwm",
    avatar: "C",
    color: "#1565c0",
    views: "720K views",
    date: "1 week ago",
    duration: "22:00",
    category: "coding",
    likes: 31000,
    subs: "620K",
    description: "Master advanced TypeScript features, patterns, and best practices.",
    icon: "💻",
    thumbnail: "https://i.ytimg.com/vi/vAk6HUiFm7c/mqdefault.jpg",
videoUrl: "/stream/v4_720p.mp4",
    comments: [
      { author: "TypeScriptDev", text: "These patterns are gold! Thanks for sharing.", likes: 750, time: "5 days ago" },
    ]
  },
  {
    id: 'v25',
    title: "World Cup 2026 – Host Cities Announced",
    channel: "GlobalNews",
    channelId: "gn",
    avatar: "G",
    color: "#e65100",
    views: "680K views",
    date: "2 days ago",
    duration: "10:20",
    category: "news",
    likes: 15200,
    subs: "890K",
    description: "Official announcement of World Cup 2026 host cities and preparations.",
    icon: "📰",
    thumbnail: "https://i.ytimg.com/vi/dQw4w9WgXcQ/mqdefault.jpg",
videoUrl: "/stream/v5_720p.mp4",
    comments: [
      { author: "SoccerFan", text: "Excited for World Cup 2026! 🇺🇸🇨🇦🇲🇽", likes: 320, time: "1 day ago" },
    ]
  }
];

// Make available globally
window.videosData = videos;

